export const APP_SETTINGS_REQUESTED = 'build/APP_SETTINGS_REQUESTED';
export const APP_SETTINGS_SUCCEED = 'build/APP_SETTINGS_SUCCEED';
export const APP_SETTINGS_FAILED = 'build/APP_SETTINGS_FAILED';
